# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.hostname = "avior-siu-dev"

  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
  config.vm.network "forwarded_port", guest: 1420, host: 1420, auto_correct: true
  config.vm.network "forwarded_port", guest: 5432, host: 15432, auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "avior-siu"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/home/vagrant/avior-siu",
    owner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775,fmode=664"]

  config.vm.provision "shell", path: "vagrant/bootstrap.sh", privileged: false

  config.vm.post_up_message = <<~MSG
    Avior SIU Dev Environment Ready!

    API:  http://localhost:3000
    UI:   http://localhost:1420
    Docs: http://localhost:3000/docs

    To start:
      vagrant ssh
      cd ~/avior-siu

      # Terminal 1 - API
      make dev-api

      # Terminal 2 - UI (real API)
      make dev-ui

    Seed accounts:
      ana@uni.edu / estudiante123
      dario@uni.edu / docente123
      carlos@uni.edu / coord123
      lucia@uni.edu / admin123
  MSG
end
